# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wso2is-pattern1-mysql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: wso2is-pattern1-mysql
    spec:
      containers:
      - name: wso2is-pattern1-mysql
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: wso2carbon
        - name: MYSQL_PASSWORD
          value: wso2carbon
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-conf
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: mysql-dbscripts
          mountPath: /home/wso2is-5.4.1-db-scripts/
        - name: mysql-initscripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-conf
          configMap:
            name: mysql-conf
        - name: mysql-dbscripts
          configMap:
            name: mysql-dbscripts
        - name: mysql-initscripts
          configMap:
            name: mysql-initscripts

