username: "<USERNAME>"
password: "<PASSWORD>"
email: "<EMAIL>"

namespace: "wso2"
svcaccount: "wso2svc-account"
serverIp: "<SERVER_IP>"
sharedDeploymentLocationPath: "<NFS_LOCATION_PATH>"
sharedTentsLocationPath: "<NFS_LOCATION_PATH>"
analytics1DataLocationPath: "<NFS_LOCATION_PATH>"
analytics2DataLocationPath: "<NFS_LOCATION_PATH>"
analytics1LocationPath: "<NFS_LOCATION_PATH>"
analytics2LocationPath: "<NFS_LOCATION_PATH>"


