# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2is-deployment
  namespace : {{ .Release.Namespace }}
spec:
  replicas: {{ default 1 .Values.wso2.deployment.wso2is.replicas }}
  minReadySeconds: {{ default 30 .Values.wso2.deployment.wso2is.minReadySeconds }}
  strategy:
    rollingUpdate:
      maxSurge: {{ default 1 .Values.wso2.deployment.wso2is.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ default 0 .Values.wso2.deployment.wso2is.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2is
  template:
    metadata:
      labels:
        deployment: wso2is
    spec:
      initContainers:
      - name: init-is-db
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z wso2is-rdbms-service-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
      {{ if .Values.wso2.centralizedLogging.enabled }}
      - name: init-logstash-plugins-install
        image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
        command:
          - /bin/bash
          - "-c"
          - |
            set -e
            ./bin/logstash-plugin install logstash-codec-multiline logstash-filter-grok
        volumeMounts:
          - name: shared-plugins
            mountPath: /usr/share/logstash/plugins/
      - name: init-elasticsearch
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of Elasticsearch Server deployment"; while ! nc -z wso2-elasticsearch-master 9200; do sleep 1; printf "-"; done; echo -e "  >> Elasticsearch server has started";']
      {{ end }}
      containers:
      - name: wso2is
        {{- if .Values.wso2.dockerRegistry }}
        image: {{ .Values.wso2.dockerRegistry }}/{{ default "wso2is" .Values.wso2.deployment.wso2is.imageName }}:{{ default "5.8.0" .Values.wso2.deployment.wso2is.imageTag }}
        {{- else if or (eq .Values.wso2.subscription.username "") (eq .Values.wso2.subscription.password "") }}
        image: wso2/{{ default "wso2is" .Values.wso2.deployment.wso2is.imageName }}:{{ default "5.8.0" .Values.wso2.deployment.wso2is.imageTag }}
        {{- else }}
        image: docker.wso2.com/{{ default "wso2is" .Values.wso2.deployment.wso2is.imageName }}:{{ default "5.8.0" .Values.wso2.deployment.wso2is.imageTag }}
        {{- end }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 9443
          initialDelaySeconds: {{ default 250 .Values.wso2.deployment.wso2is.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.wso2.deployment.wso2is.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 9443
          initialDelaySeconds: {{ default 250 .Values.wso2.deployment.wso2is.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ default 10 .Values.wso2.deployment.wso2is.readinessProbe.periodSeconds }}
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/wso2server.sh stop']
        imagePullPolicy: Always
        securityContext:
          runAsUser: 802
        ports:
        - containerPort: 9763
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: identity-server-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
        - name: identity-server-conf-axis2
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/axis2
        - name: identity-server-conf-datasources
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/datasources
        - name: identity-server-conf-identity
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/identity
        - name: shared-deployment-persistent-disk
          mountPath: /home/wso2carbon/wso2is-5.8.0/repository/deployment
        - name: shared-tenants-persistent-disk
          mountPath: /home/wso2carbon/wso2is-5.8.0/repository/tenants
      {{ if .Values.wso2.centralizedLogging.enabled }}
        - name: shared-logs
          mountPath: /home/wso2carbon/wso2is-5.8.0/repository/logs/
      - name: wso2apim-with-analytics-logstash
        image: docker.elastic.co/logstash/logstash:{{ default "7.2.0" .Values.wso2.centralizedLogging.logstash.imageTag }}
        volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/logstash/wso2-logs/
          - name: logstash-yml
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: c4-logstash-conf
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name: shared-plugins
            mountPath: /usr/share/logstash/plugins/
        env:
          - name: NODE_ID
            value: {{ default "wso2is-node" .Values.wso2.centralizedLogging.logstash.indexNodeID.wso2ISNode }}
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: logstash-elasticsearch-creds
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: logstash-elasticsearch-creds
                key: password
      {{ end }}
      serviceAccountName: {{ .Values.kubernetes.svcaccount }}
      {{ if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
      - name: wso2is-deployment-creds
      {{ end }}
      volumes:
      - name: identity-server-conf
        configMap:
          name: identity-server-conf
      - name: identity-server-conf-axis2
        configMap:
          name: identity-server-conf-axis2
      - name: identity-server-conf-datasources
        configMap:
          name: identity-server-conf-datasources
      - name: identity-server-conf-identity
        configMap:
          name: identity-server-conf-identity
      - name: shared-deployment-persistent-disk
        persistentVolumeClaim:
          claimName: is-shared-deployment-volume-claim
      - name: shared-tenants-persistent-disk
        persistentVolumeClaim:
          claimName: is-shared-tenants-volume-claim
      {{ if .Values.wso2.centralizedLogging.enabled }}
      - name: shared-logs
        emptyDir: {}
      - name: logstash-yml
        configMap:
          name: logstash-yml
      - name: c4-logstash-conf
        configMap:
          name: c4-logstash-conf
      - name: shared-plugins
        emptyDir: {}
      - name: logstash-elasticsearch-creds
        secret:
          secretName: logstash-elasticsearch-creds
      {{ end }}
