# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wso2is-with-analytics-is-analytics-1-deployment
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2is-with-analytics-is-analytics
        node: wso2is-with-analytics-is-analytics-1
    spec:
      containers:
      - name: wso2is-with-analytics-is-analytics-1
        image: docker.wso2.com/wso2is-analytics:5.5.0
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "4Gi"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 7712
          initialDelaySeconds: 250
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - nc -z localhost 7712
          initialDelaySeconds: 250
          periodSeconds: 10
        imagePullPolicy: Always
        ports:
        -
          containerPort: 9764
          protocol: "TCP"
        -
          containerPort: 9444
          protocol: "TCP"
        -
          containerPort: 7612
          protocol: "TCP"
        -
          containerPort: 7712
          protocol: "TCP"
        -
          containerPort: 11225
          protocol: "TCP"
        -
          containerPort: 10006
          protocol: "TCP"
        -
          containerPort: 11001
          protocol: "TCP"
        -
          containerPort: 11002
          protocol: "TCP"
        -
          containerPort: 11003
          protocol: "TCP"
        -
          containerPort: 11501
          protocol: "TCP"
        -
          containerPort: 8083
          protocol: "TCP"
        -
          containerPort: 4041
          protocol: "TCP"
        -
          containerPort: 10007
          protocol: TCP
        -
          containerPort: 12501
          protocol: TCP
        -
          containerPort: 13001
          protocol: TCP
        -
          containerPort: 13501
          protocol: TCP
        -
          containerPort: 14501
          protocol: TCP
        -
          containerPort: 7078
          protocol: TCP
        -
          containerPort: 6067
          protocol: TCP
        volumeMounts:
        - name: is-analytics-1-conf
          mountPath: /home/wso2carbon/kubernetes-volumes/is-analytics/conf
        - name: is-analytics-1-conf-analytics
          mountPath: /home/wso2carbon/kubernetes-volumes/is-analytics/conf-analytics
        - name: is-analytics-1-conf-spark-analytics
          mountPath: /home/wso2carbon/kubernetes-volumes/is-analytics/conf-spark-analytics
        - name: is-analytics-1-conf-axis2
          mountPath: /home/wso2carbon/kubernetes-volumes/is-analytics/conf-axis2
        - name: is-analytics-1-conf-datasources
          mountPath: /home/wso2carbon/kubernetes-volumes/is-analytics/conf-datasources
        - name: is-analytics-1-deployment-portal
          mountPath: /home/wso2carbon/kubernetes-volumes/is-analytics/conf-portal
        - name: data-persistent-disk
          mountPath: /home/wso2carbon/wso2is-analytics-5.5.0/repository/data
      serviceAccountName: "wso2svc-account"
      imagePullSecrets:
      - name: wso2creds
      volumes:
      - name: is-analytics-1-conf
        configMap:
          name: is-analytics-1-conf
      - name: is-analytics-1-conf-analytics
        configMap:
          name: is-analytics-1-conf-analytics
      - name: is-analytics-1-conf-spark-analytics
        configMap:
          name: is-analytics-1-conf-spark-analytics
      - name: is-analytics-1-conf-axis2
        configMap:
          name: is-analytics-1-conf-axis2
      - name: is-analytics-1-conf-datasources
        configMap:
          name: is-analytics-1-conf-datasources
      - name: is-analytics-1-deployment-portal
        configMap:
          name: is-analytics-1-deployment-portal
      - name: data-persistent-disk
        persistentVolumeClaim:
          claimName: is-analytics-1-data-volume-claim
